name: single-right-hand-baseline
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mediapipe==0.10.14
      - opencv-contrib-python==4.13.0.92
      - numpy==2.2.6
      - PyYAML==6.0.3
      - pytest==9.0.2
